Allure Report
melnikovmaks/automationpractice pull request #4
Opened 2022-01-24 11:26 UTC by melnikovmaks

2022-01-24 11:32 UTC, Kirill-Simonovich commented
Add description and image of your Allure report

2022-01-24 12:41 UTC, Kirill-Simonovich commented
Where can I see '@Step'?

2022-01-26 14:32 UTC, Kirill-Simonovich requested changes

2022-01-26 14:32 UTC, Kirill-Simonovich commented on src/test/java/tests/TestClass.java
> +  @Story("Check the possibility Printed Summer Dress page display for different colour dress")
Why is the name of the test and the story the same?

2022-01-26 14:32 UTC, Kirill-Simonovich commented on src/test/java/tests/TestClass.java
> +  @Epic("TESTING FOR http://automationpractice.com/ tasks")
Why @Epic and @Story used for single method?

2022-01-26 14:32 UTC, Kirill-Simonovich commented on src/main/java/data/model/TestConfigPojo.java
> +  public void setBase(String base) {
why are you writing down all the getters and setters?

2022-01-26 14:32 UTC, Kirill-Simonovich commented on src/main/java/data/model/TestConfigPojo.java
> +public class TestConfigPojo {
Where is it used?

2022-01-26 14:32 UTC, Kirill-Simonovich commented on src/main/java/data/model/TestConfigPojo.java
> +public class TestConfigPojo {
It works?

2022-01-27 12:39 UTC, merged

2022-01-29 03:24 UTC, story commented on src/test/java/tests/TestClass.java
> +  @Epic("TESTING FOR http://automationpractice.com/ tasks")
> Why @Epic and @story used for single method?

?_?